[Appearance]
color_scheme_path=/home/angel/.config/qt5ct/catppuccin-mocha-blue.conf
gui_effects=@Invalid()
icon_theme=Papirus-Dark
palette_modifications_enabled=false
style=Fusion

[Fonts]
fixed=@Variant(\0\0\0@\0\0\0\x14\0\x4\t\0@\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x44\0\0\0\0\0\0\0\0\0\0\0\0\0)
general=@Variant(\0\0\0@\0\0\0\x14\0\x4\t\0@\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x44\0\0\0\0\0\0\0\0\0\0\0\0\0)

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xff\0\0\0\0\0\0\0\0\0\0\x2\xde\0\0\x2:\0\0\0\0\x2\x4\0\0\x5V\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xff)
