# === General ===
dir=${HOME}/Downloads
max-concurrent-downloads=16
continue=true

# === HTTP/FTP/SFTP ===
max-connection-per-server=16
max-tries=10
min-split-size=8M
retry-wait=5
split=16
timeout=60
connect-timeout=30

# === BitTorrent ===
bt-max-peers=80
bt-request-peer-speed-limit=4M
max-overall-upload-limit=1K
seed-ratio=0.1
seed-time=0
enable-dht=true
enable-dht6=false
dht-listen-port=6881-6999
listen-port=6881-6999
bt-enable-lpd=true
enable-peer-exchange=true
follow-torrent=false

# === Advanced ===
console-log-level=warn
disk-cache=64M
file-allocation=falloc
log-level=error
summary-interval=0
no-file-allocation-limit=8M
disable-ipv6=true
save-session=${HOME}/.config/aria2/session.txt
input-file=${HOME}/.config/aria2/session.txt
save-session-interval=30
