include active-theme.conf

allow_remote_control yes
shell_integration no-sudo no-title
listen_on unix:/tmp/kitty

term xterm-kitty
font_size 13
font_family      JetBrainsMono Nerd Font Mono

scrollback_lines 10000
copy_on_select yes

shell zsh --login

editor nvim

hide_window_decorations titlebar-only
window_padding_width 1 5 2 2

confirm_os_window_close 0
enable_audio_bell no

cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0
cursor_stop_blinking_after 0

# cursor_trail 1         # disabled: lag on Intel HD 3000
# cursor_trail_decay 0.01 0.5
# cursor_trail_start_threshold 0

background_opacity 1.0

tab_bar_edge top
tab_bar_style fade
tab_fade 1
tab_bar_min_tabs 1

kitty_mod ctrl+shift

map ctrl+shift+u goto_layout tall
map ctrl+shift+i goto_layout fat
map ctrl+shift+o goto_layout stack

tab_title_template "{session_name or tab.active_wd.rsplit('/', 1)[-1] or '~'}"

map ctrl+shift+,   load_config_file

map ctrl+shift+enter new_window
map ctrl+shift+l next_window
map ctrl+shift+h previous_window

map ctrl+j kitten pass_keys.py bottom ctrl+j "nvim"
map ctrl+k kitten pass_keys.py top    ctrl+k "nvim"
map ctrl+h kitten pass_keys.py left   ctrl+h "nvim"
map ctrl+l kitten pass_keys.py right  ctrl+l "nvim"

map ctrl+shift+alt+h resize_window narrower
map ctrl+shift+alt+l resize_window wider
map ctrl+shift+alt+k resize_window taller
map ctrl+shift+alt+j resize_window shorter 3

map kitty_mod+w close_window

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set readonly nolist' +'$' -
map kitty_mod+z show_scrollback
map kitty_mod+i launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay /bin/zsh -c "NVIM_APPNAME=neobean SIMPLER_SCROLLBACK=deeznuts nvim +$ +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set number relativenumber' +'$' -"

map ctrl+shift+s save_as_session --use-foreground-process --relocatable

map ctrl+b>d goto_session sessions/dotfiles.kitty-session
map ctrl+b>h goto_session sessions/home.kitty-session
map ctrl+b>1 goto_session sessions/networking.kitty-session
map ctrl+b>o goto_session sessions/obsidian.kitty-session
map ctrl+b>s goto_session sessions/scripts.kitty-session
map ctrl+b>l goto_session -1

tab_bar_filter session:~ or session:^$
map ctrl+shift+t launch --type=tab --cwd=current

map ctrl+shift+up    scroll_line_up
map ctrl+shift+down  scroll_line_down
map ctrl+shift+home  scroll_home
map ctrl+shift+end   scroll_end
